version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  redis-stat:
    image: insready/redis-stat
    container_name: redis-stat
    command: redis-stat redis:6379 --daemon --server=63790
    ports:
      - "63790:63790"
    depends_on:
      - redis

networks:
  defult:
    external:
      name: redis-net